#!/usr/bin/env bash
# This script transfers a file from the client machine to a remote server using SCP.
# Usage: ./0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY
#Transfer a File to your server

if [ $# -lt 4 ]
then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
